### ISSUE TITLE
Modal title header 오류 해결

### ISSUE THREAD

**Issue by dayeon5470** [aicers/frontary#118]
![image (1)](https://github.com/aicers/frontary/assets/110362826/1a55a6ee-258d-4243-a6d7-7bb51688f5fe)

**Comment by sophie-cluml** [comment]
@dayeon5470 to-do list 의 값들을 등록해주세요.

**Comment by sophie-cluml** [comment]
@dayeon5470 위의 코멘트 확인해주세요
