### ISSUE TITLE
AI Model menu Clumit 디자인 적용

### ISSUE THREAD

**Issue by jinjoolee07** [aicers/frontary#133]
해당 컴포넌트: `SelectMini`, `Radio`

<img width="704" alt="Screenshot 2024-08-12 at 6 02 42 PM" src="https://github.com/user-attachments/assets/46075eeb-3e30-406c-a62c-713646d2f126">
<img width="361" alt="Screenshot 2024-08-12 at 6 03 20 PM" src="https://github.com/user-attachments/assets/31ba41e4-476a-485f-96e5-209b2667b8ce">
<img width="942" alt="Screenshot 2024-08-12 at 6 03 29 PM" src="https://github.com/user-attachments/assets/0cf63f6a-7e98-4657-ba78-628b800ee316">
<img width="909" alt="Screenshot 2024-08-12 at 6 03 49 PM" src="https://github.com/user-attachments/assets/1b53249e-2b9e-4907-b4ed-0d6d06f38109">
<img width="986" alt="Screenshot 2024-08-12 at 6 04 46 PM" src="https://github.com/user-attachments/assets/49c3da4b-40a4-4955-806e-d100e23066ed">

**Comment by jinjoolee07** [comment]
On hold due to not being able to view AI Model (By Round/By Model): IP, Column, 1:N, and Trend in Time. More details here: [Issues](https://github.com/aicers/topshot/issues).

**Comment by sophie-cluml** [comment]
@jinjoolee07 Could you remove the link to a private page?
