### ISSUE TITLE
Modify clumit dropdown ui

### ISSUE THREAD

**Issue by jinjoolee07** [aicers/frontary#174]
Description
Apply the following UI adjustments to all dropdowns across the Clumit platform to align with the intended design. So far, these issues were observed in the Event and Report menus. However, there may be other instances across the platform, so a thorough review will be necessary to ensure consistency.

**Screenshot**
<img width="1604" alt="379189471-780bb579-fc22-424f-90c4-42bddb1fc8e5" src="https://github.com/user-attachments/assets/898e20a5-5b9d-4fc7-bad5-79e3dac5e060">

**Comment by sophie-cluml** [comment]
<img width="926" alt="image" src="https://github.com/user-attachments/assets/de59b0fe-6452-4023-9c11-9d3cf2e4a0f6">

위와 같이 trigger가 걸려있으나 자동으로 이 이슈가 닫아지지 않았습니다. 수동으로 닫습니다.
