### ISSUE TITLE
Add clippy lint option to check the use of `unwrap`

### ISSUE THREAD

**Issue by dayeon5470** [aicers/frontary#192]
## Background
- The development rules for our product say that we should use `expect` instead of `unwrap` in situations where we are confident that panic will not necessarily occur.
- We should also make sure that the code we write in the future follows the same rules. 
- Therefore, we should proceed with the modification as shown below

## Task
- Add a lint option to the Clippy part of ci.yml: -W clippy::unwrap_used

**Comment by sophie-cluml** [comment]
Since we chose not to add an additional warning item to clippy in the discussion repository, let me close this.
