### ISSUE TITLE
Clarify and Validate allowed_extensions Handling

### ISSUE THREAD

**Issue by jinjoolee07** [aicers/frontary#212]
**Details**
There is ambiguity around how `allowed_extensions` should handle extensions—specifically, whether they should include a leading `.` or not, which needs to be clarified and documented. Additionally, there is no validation to ensure extensions are valid (e.g., no spaces, proper characters) or consistent. A decision is needed on the expected behavior (e.g., requiring a .), along with implementing appropriate validation and normalization, supported by clear documentation.

Three potential handling options were suggested:

~~1. Allow extensions starting with a `.` and validate the input to exclude invalid ones.~~
~~2. Allow extensions starting without a `.` and validate the input to exclude invalid ones.~~
3. Allow any extensions and automatically add `.` where necessary.

In all cases, documentation will be required.

**Comment by sehkone** [comment]
I vote for number 3.
