### ISSUE TITLE
Modify Clumit (WholeList, Sort, SelectMini, CheckBox) component

### ISSUE THREAD

**Issue by jinjoolee07** [aicers/frontary#95]
해당 컴포넌트 : `Sort`, `SelectMini`, `CheckBox`

<img width="773" alt="Screenshot 2024-06-12 at 3 17 00 PM" src="https://github.com/aicers/frontary/assets/32283688/9ca2d5e2-5f45-445b-9a87-c009fb61e404">

<img width="1372" alt="Frame 427319492" src="https://github.com/aicers/frontary/assets/32283688/d64528d4-249f-454c-9783-04fb96a503d8">

**Comment by sophie-cluml** [comment]
@jinjoolee07 private repository 로의 링크는 public repository에 달지 않아야해서, 제거 부탁드립니다.

**Comment by dayeon5470** [comment]
https://github.com/aicers/frontary/pull/115 완료
