### ISSUE TITLE
Modify Clumit Frontary components

### ISSUE THREAD

**Issue by dayeon5470** [aicers/frontary#97]
frontary에서 수정사항

checkbox - CheckBox
radio - Radio
tab_menu - TabMenu
modal - Modal

- [x] Checkbox
- [x] Radio
- [x] Tab menu
- [x] Modal

Tab Menu + Checkbox
<img width="656" alt="Screenshot 2024-06-12 at 3 17 29 PM" src="https://github.com/aicers/frontary/assets/32283688/6b7d59a7-bf3f-4c3d-88b1-6f012e348d50">
<img width="655" alt="Screenshot 2024-06-12 at 3 17 08 PM" src="https://github.com/aicers/frontary/assets/32283688/8b9e5f6e-d008-444f-9b8b-536ed918607f">

Modal
<img width="633" alt="Screenshot 2024-06-20 at 7 38 37 AM" src="https://github.com/aicers/frontary/assets/32283688/589f2d9f-41ba-479f-8e7e-51a1d38eed78">

Radio
<img width="662" alt="Screenshot 2024-06-20 at 7 41 05 AM" src="https://github.com/aicers/frontary/assets/32283688/6a776851-4690-43b7-b798-5bb08b63f0be">

**Comment by dayeon5470** [comment]
#https://github.com/aicers/aice-web/issues/503

**Comment by jinjoolee07** [comment]
https://github.com/aicers/aice-web/issues/503
