### ISSUE TITLE
Create `Kind::MoreActionBasic` in `select::mini`

### ISSUE THREAD

**Issue by marioCluml** [aicers/frontary#99]
Create a new variant `Kind::MoreActionBasic`  in `select::mini`, because we need a more action that only displays texts, without images, and showed upon clicking  `more-action-dots.png`. What we want to do is to create a component that acts the same as `Kind::MoreAction`, but only without image. Currently existing `Kind::MoreActionNoImage` looks like it serves the purpose, but `Kind::MoreActionNoImage` does not make use of `more-action-dots.png`.

**Comment by sophie-cluml** [comment]
@marioCluml this is a public repository, so you should not attach screenshots that would expose information about non-public repositories. Your screenshot contains such info. Please crop that info out of the screenshot.

**Comment by marioCluml** [comment]
> @marioCluml this is a public repository, so you should not attach screenshots that would expose information about non-public repositories. Your screenshot contains such info. Please crop that info out of the screenshot.

My apologies, I will crop it right away

**Comment by sophie-cluml** [comment]
To make it work, it seems like we need part like this as well: https://github.com/aicers/frontary/blob/main/src/select/mini.rs#L269-L290
